import type { Options } from "./types";

export const demo: Record<string, Options> = {
  条形图: {
    type: "interval",
    autoFit: true,
    data: {
      type: "fetch",
      value:
      "https://gw.alipayobjects.com/os/bmw-prod/f129b517-158d-41a9-83a3-3294d639b39e.csv",
      format: "csv",
    },
    encode: { x: "state", y: "population", color: "age" },
    transform: [
      { type: "sortX", by: "y", reverse: true, slice: 6 },
      { type: "dodgeX" },
    ],
    scale: { y: { nice: true } },
    axis: { y: { labelFormatter: "~s" } },
    interaction: {
      tooltip: { shared: true },
      elementHighlightByColor: { background: true },
    },
    title: {
      title: "Population by age and state",
      subtitle: "It shows the population of U.S. by age and state.",
    },
    theme: { view: { viewFill: "white" } },
  },
  折线图: {
    type: "line",
    autoFit: true,
    data: {
      type: "fetch",
      value:
      "https://gw.alipayobjects.com/os/bmw-prod/cb99c4ab-e0a3-4c76-9586-fe7fa2ff1a8c.csv",
    },
    encode: {
      x: d => new Date(d.date).getFullYear(),
      y: "price",
      color: "symbol",
    },
    transform: [{ type: "groupX", y: "mean" }],
    labels: [
      { text: "price", transform: [{ type: "overlapDodgeY" }], fontSize: 10 },
    ],
    tooltip: { items: [{ channel: "y", valueFormatter: ".1f" }] },
    theme: { view: { viewFill: "white" } },
  },
  雷达图: {
    type: "line",
    autoFit: true,
    data: [
      {
        name: "Jordan",
        Points: 30.1,
        Rebounds: 6.2,
        Assists: 5.3,
        Steals: 2.3,
        Blocks: 0.8,
      },
      {
        name: "LeBron James",
        Points: 27,
        Rebounds: 7.4,
        Assists: 7.4,
        Steals: 1.6,
        Blocks: 0.8,
      },
    ],
    encode: {
      position: ["Points", "Rebounds", "Assists", "Steals", "Blocks"],
      color: "name",
    },
    scale: {
      position: { domainMin: 0, nice: true },
      position1: { domainMin: 0, nice: true },
      position2: { domainMin: 0, nice: true },
      position3: { domainMin: 0, nice: true },
      position4: { domainMin: 0, nice: true },
    },
    coordinate: { type: "radar" },
    style: { lineWidth: 1.5, strokeOpacity: 0.4 },
    axis: {
      position: {
        zIndex: 1,
        titleFontSize: 10,
        titleSpacing: 8,
        label: true,
        labelFill: "#000",
        labelOpacity: 0.45,
        labelFontSize: 10,
        line: true,
        lineFill: "#000",
        lineOpacity: 0.25,
      },
      position1: {
        zIndex: 1,
        titleFontSize: 10,
        titleSpacing: 8,
        label: true,
        labelFill: "#000",
        labelOpacity: 0.45,
        labelFontSize: 10,
        line: true,
        lineFill: "#000",
        lineOpacity: 0.25,
      },
      position2: {
        zIndex: 1,
        titleFontSize: 10,
        titleSpacing: 8,
        label: true,
        labelFill: "#000",
        labelOpacity: 0.45,
        labelFontSize: 10,
        line: true,
        lineFill: "#000",
        lineOpacity: 0.25,
      },
      position3: {
        zIndex: 1,
        titleFontSize: 10,
        titleSpacing: 8,
        label: true,
        labelFill: "#000",
        labelOpacity: 0.45,
        labelFontSize: 10,
        line: true,
        lineFill: "#000",
        lineOpacity: 0.25,
      },
      position4: {
        zIndex: 1,
        titleFontSize: 10,
        titleSpacing: 8,
        label: true,
        labelFill: "#000",
        labelOpacity: 0.45,
        labelFontSize: 10,
        line: true,
        lineFill: "#000",
        lineOpacity: 0.25,
      },
    },
    interaction: { tooltip: { series: false } },
    title: "Jordan vs LeBron James NBA Stats Comparison",
    theme: { view: { viewFill: "white" } },
  },
};
